### ISSUE TITLE
IOS9 Beta 3

### ISSUE THREAD

**Issue by plarner** [typicaljoe/taffydb#98]
Hi, IOS9 obviously is still in beta but just a heads up there appears to be an issue visible on the demo page on IOS9. http://www.javascriptoo.com/taffydb. people().count() returns 0, people().first() is false and the others are empty arrays.

**Comment by NancyNickerson** [comment]
Is it fixed in the latest OS 9 beta 5. 
Has anyone tested the issue in the latest beta release.

**Comment by ltullman** [comment]
Still broken in iOS 9 GM.  Looks like isArray is returning false for cases that previously returned true.  I'm not sure what the proper solution should be here.

**Comment by ltullman** [comment]
I worked around it by doing the following:  

1.  Define a sortArgs method to convert the implicit Arguments object to a true array:
  function sortArgs(args) {
    var v = Array.prototype.slice.call(args);
    return v.sort();
  }

2.  Replace the 4 instances where arguments are used with sortArgs(arguments).  

Seems to be working okay now.

**Comment by ltullman** [comment]
https://github.com/typicaljoe/taffydb/pull/101

**Comment by plarner** [comment]
Thanks for the work around. Still happening in IO9 Gm unfortunately! Likely there will be a patch soon from Apple.

**Comment by ltullman** [comment]
Yeah I noticed it in the iOS 9 GM as well so put in the workaround for our hybrid app that uses Taffy.  Will be interesting to see if this breaks a lot of folks when iOS 9 goes live today.

**Comment by plarner** [comment]
@ltullman I've applied your work around but i'm still having a few issues, any chance you can help see if its possible there are any other places the sortArgs function might need applying? Iv'e had a go myself but i'm not sure i understand the core of why its happening. Is it something to do with the typeOf replacement function?

**Comment by ltullman** [comment]
It's possible I missed some of them.  Did you apply the Pull Request from here: https://github.com/typicaljoe/taffydb/pull/101?  Or did you just change the places I referenced in the comment above?  I think the PR got all of them while the comment may have missed a few.  

The underlying issue that caused this was that the typeOf method was checking if Arguments was an array and this check was now failing on this line:

 if ( typeof v.length === 'number' && !(v.propertyIsEnumerable( 'length' )) )

As far as I can tell, Safari 9 and Mobile Safari 9 changed how the length property was treated on an Arguments object and therefore didn't think it was a true array.  I verified this by testing in Chrome and the v.propertyIsEnumerable('length') returns true on Safari 9 and false on Chrome.

**Comment by plarner** [comment]
Brilliant, thanks alot. Yeah, I had just changed in the places outlined in your comment but now its working fine.
